### ISSUE TITLE
Ability to bulk add apps

### ISSUE THREAD

**Issue by Just5KY** [lolamtisch/PreWrap#11]
It will be really nice to have an option to bulk select multiple apps from the list and enable them at once.
or at least if the window won't disappear after adding one app.

Selecting apps one by one is a pain

![Recording 2022-07-08 at 01 21 56](https://user-images.githubusercontent.com/71321862/177860456-559d9059-64a4-4f3f-9904-818af98ba6bb.gif)

**Comment by lolamtisch** [comment]
The Browser forces the window to close to accept the permissions and there is no way around it. Bulk accepting the permissions afterwards would result in a weird userflow, where you first select all pages you want and then you need to press another button to trigger the permission update.
