### ISSUE TITLE
YouTube presence not working

### ISSUE THREAD

**Issue by rikkdekkard** [lolamtisch/PreWrap#13]
I'm on Firefox, and for the last couple of weeks I'm getting "No presence active" message on YouTube (the extension works elsewhere).
Tried disabling and re-enabling the extension (which usually worked in the past), re-downloading the presence and even re-installing the addon itself, but to no avail.
Surprisingly, the Discord RPC Pack extension _does_ work.

**Comment by henrik9999** [comment]
Can you check if it's works with the latest version

**Comment by rikkdekkard** [comment]
It does not, unfortunately 🙁

**Comment by rikkdekkard** [comment]
The latest update seems to have fixed it, so I'm closing the issue.
