### ISSUE TITLE
LinusTechTips is broken

### ISSUE THREAD

**Issue by mm12** [lolamtisch/PreWrap#2]
I have the "LinusTechTips" page enabled. I have the desktop app running (tested with Youtube Music, it worked), but the LTT Forum doesn't show up when I try.

**Comment by lolamtisch** [comment]
We dont maintain the presences. But I looked into it and made a Pull Request with a fix. After they merge it it should fix itself with the next release (every Sunday).

**Comment by henrik9999** [comment]
Should be fixed
