### ISSUE TITLE
DashNet / Cookie Clicker doesn't work

### ISSUE THREAD

**Issue by FayneAldan** [lolamtisch/PreWrap#5]
The extension for DashNet / Cookie Clicker doesn't work. I've already tested it on PreMiD and found it working fine on there. With PreWrap it shows correctly on first load, but it stops working shortly after.

**Comment by lolamtisch** [comment]
The Presence code like it is theoretically should not work. I added a workaround to fix that. The release with the fix should appear in the next few hours.

**Comment by FayneAldan** [comment]
Just thought I'd reference the fix commit: 22e38a0a5e75a1da9d2f36cc8d489ceb0edfda4a
